---
version: "3"
services:
  main:
    image: ghcr.io/paolotremadio/tailscale-gateway:latest
    container_name: tailscale-gateway
    volumes:
      - $PWD:/home/node/app-config:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Europe/London
    restart: always
    depends_on:
      - caddy
  caddy:
    image: caddy:alpine
    container_name: tailscale-gateway-caddy
    volumes:
      - $PWD:/config:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Europe/London
      - CADDY_ADMIN=0.0.0.0:2019
    ports:
      - 80:80
    #      - 2019:2019
    restart: always
